eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: 'http://discovery:8761/eureka/'
spring:
  cloud:
    gateway:
      routes:
      - id: webpos-product-service
        predicates:
        - Path=/product/**
        uri: lb://webpos-product-service
      - id: webpos-ordering-service
        predicates:
        - Path=/cart/**
        uri: lb://webpos-ordering-service
