eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: 'http://discovery:8761/eureka/'
spring:
  cloud:
    gateway:
      routes:
      - id: webpos-product-service
        predicates:
        - Path=/product/**
        uri: lb://webpos-product-service
        filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
      - id: webpos-ordering-service
        predicates:
        - Path=/cart/**
        uri: lb://webpos-ordering-service
        filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 20
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
